# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Lingua-EN-Inflect
version:      0.02
version_from: lib/Template/Plugin/Lingua/EN/Inflect.pm
installdirs:  site
requires:
    Lingua::EN::Inflect:           0
    Template:                      2.07
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
